<a href="https://colab.research.google.com/github/divyansh-tripathi7/ml_ps/blob/main/AdSalePred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ad Sale prediction using logistic regression 


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving custData.csv to custData.csv


In [ ]:
dataset = pd.read_csv('custData.csv')

In [ ]:
print(dataset.shape)
print(dataset.head(11))

(499, 3)
    41   60991  0
0   57   14433  1
1   59  181605  0
2   60   17809  0
3   60   85376  0
4   77  114782  0
5   62   59291  1
6   50   39882  0
7   41   72612  1
8   43  158423  0
9   19   81097  0
10  44   74472  1


In [ ]:
X = dataset.iloc[:,:-1].values
X

array([[    57,  14433],
       [    59, 181605],
       [    60,  17809],
       [    60,  85376],
       [    77, 114782],
       [    62,  59291],
       [    50,  39882],
       [    41,  72612],
       [    43, 158423],
       [    19,  81097],
       [    44,  74472],
       [    74,  10827],
       [    76,  94267],
       [    55, 136134],
       [    46,  18661],
       [    36,  81717],
       [    45, 139951],
       [    52,  19158],
       [    67, 172572],
       [    63, 140702],
       [    28, 158440],
       [    20, 138616],
       [    40, 115025],
       [    26,  38495],
       [    80, 100263],
       [    46,  16571],
       [    41, 134500],
       [    59,  22548],
       [    25, 117173],
       [    50, 110849],
       [    43, 123802],
       [    67, 130958],
       [    72, 186982],
       [    58, 104700],
       [    59,  51091],
       [    63, 199210],
       [    56, 124303],
       [    41,  73672],
       [    21, 105775],
       [    54,  37569],


In [ ]:
Y = dataset.iloc[:,-1].values
Y

array([1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train , y_test = train_test_split(X,Y,test_size= 0.25, random_state = 0)

In [ ]:
## feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state= 0)
model.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
##prediction 

In [ ]:
age = int(input("Enter new customer Age: "))
sal = int(input("enter new customer's salary : "))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print(" customer will buy the  product")
if result == 0:
  print(" customer will not buy the  product")
  

Enter new customer Age: 69
enter new customer's salary : 88888888
[0]
 customer will not buy the  product


In [ ]:
#confusion matrix
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [1 1]
 [1 0]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]]


In [ ]:
# evaluating model
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix: ")
print(cm)

print("accuracy of model : {0}%".format(accuracy_score(y_test,y_pred)*100))

Confusion Matrix: 
[[53 12]
 [48 12]]
accuracy of model : 52.0%
